import "server-only";

import { getStore } from "@netlify/blobs";

/**
 * Waitlist storage backed by Netlify Blobs.
 *
 * We moved off Supabase after the free-tier project auto-paused and
 * every signup started returning 500. Netlify Blobs is native to the
 * hosting platform, always available on production deploys, has no
 * cold-start pause behaviour, and needs zero external configuration —
 * the Netlify runtime injects the required env automatically.
 *
 * Data model:
 *   - One JSON blob per email (key: canonical lowercased email). Value:
 *     `{ email, country, painPoint?, referredBy?, refCode, position,
 *        createdAt }`. `position` is monotonic across all inserts —
 *     users see it as "founding member #N".
 *   - Store name `"waitlist"` — routes read/write the same store so
 *     stats + signup share a single source of truth.
 *
 * Counter:
 *   - Position is generated by atomically reading + writing a
 *     "__meta:counter" blob. Netlify Blobs uses last-write-wins on
 *     concurrent writes; the race is bounded (two signups at the same
 *     millisecond might collide and one gets a duplicate position).
 *     Waitlist traffic is low enough that this is acceptable — we
 *     accept the trade-off vs the operational overhead of running a
 *     real DB for what is effectively a 3-field append-only log.
 */

const STORE_NAME = "waitlist";
const COUNTER_KEY = "__meta:counter";

export interface WaitlistEntry {
  email: string;
  country: string;
  painPoint?: string;
  referredBy?: string;
  refCode: string;
  position: number;
  createdAt: string;
}

function normEmail(email: string): string {
  return email.toLowerCase().trim();
}

/**
 * Netlify Blobs store. `consistency: "strong"` is required for the
 * idempotent-signup + counter logic — the default is eventually
 * consistent, so a duplicate POST issued seconds after the first
 * would see an empty read and issue a fresh position + refCode
 * instead of returning the existing entry. Strong reads are ~5-10ms
 * slower per call but correctness > latency for a signup endpoint
 * with single-digit QPS.
 *
 * Netlify Blobs auto-connects inside the Netlify Functions runtime
 * (which is where our /api routes run under @netlify/plugin-nextjs)
 * so no siteID/token is needed here.
 */
function store() {
  return getStore({ name: STORE_NAME, consistency: "strong" });
}

/** Generate a URL-safe 8-char ref code. */
function generateRefCode(): string {
  const bytes = new Uint8Array(6);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode.apply(null, Array.from(bytes)))
    .replace(/\+/g, "A")
    .replace(/\//g, "B")
    .replace(/=/g, "")
    .slice(0, 8);
}

/** Read + increment the position counter atomically-enough. */
async function nextPosition(s: ReturnType<typeof store>): Promise<number> {
  const current = await s.get(COUNTER_KEY, { type: "json" });
  const currentN =
    typeof current === "object" &&
    current !== null &&
    "value" in current &&
    typeof (current as { value: unknown }).value === "number"
      ? ((current as { value: number }).value as number)
      : 0;
  const next = currentN + 1;
  await s.setJSON(COUNTER_KEY, { value: next });
  return next;
}

/**
 * Insert-or-return-existing. Mirrors the previous Supabase semantics
 * so the route handler's response shape doesn't change.
 *   - `{ inserted: true, entry }`   → brand-new signup
 *   - `{ inserted: false, entry }`  → email already on the list;
 *                                     re-submits are idempotent
 */
export async function upsertWaitlistEntry(input: {
  email: string;
  country: string;
  painPoint?: string;
  referredBy?: string;
}): Promise<{ inserted: boolean; entry: WaitlistEntry }> {
  const s = store();
  const key = normEmail(input.email);

  const existing = await s.get(key, { type: "json" });
  if (existing && typeof existing === "object" && "position" in existing) {
    return { inserted: false, entry: existing as WaitlistEntry };
  }

  const entry: WaitlistEntry = {
    email: key,
    country: input.country,
    painPoint: input.painPoint,
    referredBy: input.referredBy,
    refCode: generateRefCode(),
    position: await nextPosition(s),
    createdAt: new Date().toISOString(),
  };
  await s.setJSON(key, entry);
  return { inserted: true, entry };
}

export interface WaitlistStatsSignup {
  position: number;
  email: string;
  country: string;
  createdAt: string;
  referredBy: string | null;
}

export interface WaitlistStats {
  total: number;
  last24h: number;
  last7d: number;
  latestAt: string | null;
  countries: { country: string; count: number }[];
  signups: WaitlistStatsSignup[];
}

/**
 * Aggregate stats for the /stats dashboard. Scans every entry in the
 * blob store — cheap while the waitlist is under a few thousand
 * entries. Revisit with a materialised summary blob if it grows past
 * that.
 */
export async function getWaitlistStatsFromBlobs(): Promise<WaitlistStats> {
  const s = store();
  const now = Date.now();
  const dayMs = 24 * 60 * 60 * 1000;

  const listing = await s.list();
  const countries = new Map<string, number>();
  const signups: WaitlistStatsSignup[] = [];
  let last24h = 0;
  let last7d = 0;
  let latestAt: string | null = null;
  let latestMs = -Infinity;

  for (const item of listing.blobs) {
    if (item.key === COUNTER_KEY) continue;
    const value = await s.get(item.key, { type: "json" });
    if (!value || typeof value !== "object" || !("email" in value)) continue;
    const entry = value as WaitlistEntry;
    countries.set(entry.country, (countries.get(entry.country) ?? 0) + 1);
    signups.push({
      position: entry.position,
      email: entry.email,
      country: entry.country,
      createdAt: entry.createdAt,
      referredBy: entry.referredBy ?? null,
    });
    const createdMs = Date.parse(entry.createdAt);
    if (Number.isFinite(createdMs)) {
      if (now - createdMs < dayMs) last24h += 1;
      if (now - createdMs < 7 * dayMs) last7d += 1;
      if (createdMs > latestMs) {
        latestMs = createdMs;
        latestAt = entry.createdAt;
      }
    }
  }

  // Newest-first ordering for the dashboard signup list.
  signups.sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));

  return {
    total: signups.length,
    last24h,
    last7d,
    latestAt,
    countries: Array.from(countries.entries())
      .map(([country, count]) => ({ country, count }))
      .sort((a, b) => b.count - a.count),
    signups,
  };
}
